-- AlterTable
ALTER TABLE "books" ALTER COLUMN "author" DROP DEFAULT,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "genre" DROP DEFAULT,
ALTER COLUMN "price" DROP DEFAULT,
ALTER COLUMN "title" DROP DEFAULT;
